version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:10.19.0

jobs:
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm install
          npm build
workflows:
  my-custom-workflow:
    jobs:
      - build
