version: 2.1
jobs:
  build:
    machine: 
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          docker build . -t image-ci-cd
          docker run -p 41976:8080 -d image-ci-cd
          sleep 2
          curl -I http://localhost:41976/ |grep "200 OK"
          
workflows:
  my-custom-workflow:
    jobs:
      - build
