version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:10.19.0

jobs:
  build:
    machine: 
      image: ubuntu:latest
    steps:
      - checkout
      - run: |
          docker build . -t image-ci-cd
          docker run -p 41976:8080 -d image-ci-cd
          curl -I http://localhost:41976/ |grep "200 OK"
          
workflows:
  my-custom-workflow:
    jobs:
      - build
